### PR TITLE
Update world.py

### PR DESCRIPTION
**Pull request by alexandrelefourner**
- Updating the available cells at each step to avoid a bug of food placed under the snake.
- Fixing the wrong reward assignment in case of food place right in front of  a snake before its movement (and thus not broadcast during observation).

### CODE REVIEW

**Comment by nicomon24** [comment]
Thanks for this bugfix! Reasoning more about this, wouldn't it be better to avoid storing the `self.available_positions` in the first place? Since we use it just to place food, we could simply do a loop over snakes to update the positions in the `place_one_food` function.

**Comment by alexandrelefourner** [comment]
I think you idea to use `self.available_positions` is not a bad one and should be kept.

Since you already iterate through the snakes at first, doing another iteration would not be efficient.
Instead, what I proposed was to store the positions into a variable called `self.base_available_position` which is used to reset your `self.available_positions`. Next, `self.available_positions` is updated with the snake iteration and used by the `place_one_food` function.

The function does not need to reiterate and simply takes the variable. It means more memory is occupied (but not that much) and less time to compute each step. The difference might not seem significative, but the more snake you would add in the iteration, the longer it would becomes.

**Comment by nicomon24** [comment]
Looking at your code, you are doing the update of `self.available_position` at each step; considering that structure is used only when placing a new food object (which should be a sparse event), wouldn't it be better to just do it when placing the food? (yes it would require to loop again over all the snakes but the number of ops you do is the nearly the same).
In the case of a large grid this is even worse (you don't want to do it at each iteration).
The `self.base_available_positions` is instead a good thing to have since that doesn't change over time. 

If it's ok with you I'm merging your pull request and updating the code with this slight change (Thanks again)

**Comment by alexandrelefourner** [comment]
Indeed, you're right! It's better to calculate this when adding the food considering the sparse aspect.

You can merge, you're welcome :)

**Pull request merged**
